# Site
repository:  https://github.com/israelavilamares
favicon: favicon.ico

# Content configuration version
version: 2

# Personal info
name: israel joaquin avila mares 
title: ING Informatica
email: israeljoaquinavilamares@gmail.com
#website: 

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: https://twitter.com/israelavil51653
#github_username:  https://github.com/israelavilamares
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
#facebook_username: https://m.facebook.com/people/Israel-Joaquin-Avila-Mares/100009842228218/
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: https://www.youtube.com/@aprediendoTecnologias8390
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: perfil.jpg
about_content: | # this will include new lines to allow paragraphs
 Hello, I am Israel, a seven semester student in the computer engineering degree along i have developed several proyect 
  I am most skilled in: <mark>data base</mark> and <mark> interface design </mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Particulas, regresion-polinomial, Odontosaurio_jn2.0 
        link:  https://github.com/israelavilamares/particulas
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          El mundo se puede cambiar en 140 caracteres.
        description: | # this will include new lines to allow paragraphs
         it for me is a way learn and i show it learned and share. 

#  - title: Experience # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: left
#        title: The Boring Company
#        link: boringcompany.com
#        # link_text: boringcompany.com
#        sub_title: Senior Network System Administrator
#        caption: November 2017 - Present
#        quote: >
#          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
#        description: | # this will include new lines to allow paragraphs
#            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: UNIVERSIADAD DE GUADALAJARA
        caption: 2020 - 2024
        sub_title: CENTRO UNIVERSITARIO DE CIENCIAS EXACTAS E INGENIERIAS - informatica.
        quote: >
          bishop of Guadalajara, on November 3, 1792, the Royal University of Guadalajara was inaugurated, which chronologically became the second of the New Spain
        description: | # this will include new lines to allow paragraphs
          during my this time in the university i learned in base to works and proyect in current technologies
          also i have course about container(Docker), the cloud ,microservices, data privacy y AI 
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I spent a lot of my free time with my family and friend enjoying besides me like leave to walk and run for known many place.
      my favorite activities are 
      -run 
      -walk
      ![forest](C:/Users/isra/Desktop/programcion para internet/CVgithub/centinela.png "forest")
      -watch videos
      -eat
      
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
